web:
 upload-path: F:/
# spring配置
spring:
 datasource:
  url: jdbc:mysql://127.0.0.1:3306/nahida_anime
  username: root
  password: 123456
  driver-class-name: com.mysql.cj.jdbc.Driver
 web:
  resources:
   static-locations: file:${web.upload-path}
#  端口号
server:
 port: 1314
 address: 0.0.0.0
#  变量
Nahida:
 project-name: Anime
 media-path: F:/anime